// Script para generar instrucciones de
// inserción de proveedores en MySQL

const names = [
    'Transportes', 
    'Distribuciones', 
    'Logística',
    'Repuestos',
    'Suministros',
    'Importaciones',
    'Exportaciones'
]

const surnames = [
    'García',
    'González',
    'Rodríguez',
    'Fernández',
    'López',
    'Martínez',
    'Sánchez',
    'Pérez',
    'Gómez',
    'Martin',
    'Jiménez',
    'Ruiz',
    'Hernández',
    'Diaz',
    'Moreno',
    'Muñoz',
    'Álvarez',
    'Romero',
    'Alonso',
    'Gutiérrez',
    'Navarro',
    'Torres',
    'Domínguez',
    'Vázquez',
    'Ramos',
    'Gil',
    'Ramírez',
    'Serrano',
    'Blanco',
    'Molina',
    'Morales',
    'Suarez',
    'Ortega',
    'Delgado',
    'Castro',
    'Ortiz',
    'Rubio',
    'Marín',
    'Sanz',
    'Núñez',
    'Iglesias',
    'Medina',
    'Garrido',
    'Cortes',
    'Castillo',
    'Santos',
    'Lozano',
    'Guerrero',
    'Cano',
    'Prieto',
    'Méndez',
    'Cruz',
    'Calvo',
    'Gallego',
    'Vidal',
    'León',
    'Márquez',
    'Herrera',
    'Peña',
    'Flores',
    'Cabrera',
    'Campos',
    'Vega',
    'Fuentes',
    'Carrasco',
    'Diez',
    'Caballero',
    'Reyes',
    'Nieto',
    'Aguilar',
    'Pascual',
    'Santana',
    'Herrero',
    'Lorenzo',
    'Montero',
    'Hidalgo',
    'Giménez',
    'Ibáñez',
    'Ferrer',
    'Duran',
    'Santiago',
    'Benítez',
    'Mora',
    'Vicente',
    'Vargas',
    'Arias',
    'Carmona',
    'Crespo',
    'Román',
    'Pastor',
    'Soto',
    'Sáez',
    'Velasco',
    'Moya',
    'Soler',
    'Parra',
    'Esteban',
    'Bravo',
    'Gallardo',
    'Rojas'
];

let vendors = [];

for (i = 0; i < 200; i++) {
    const name = names[Math.floor(Math.random() * names.length)];
    const surname = surnames[Math.floor(Math.random() * surnames.length)];
    vendors.push({
        nombre: name + ' ' + surname + ', S.L.',
        cif: 'A12345566'
    })
}

console.log(vendors);